/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/_auth.register'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppMoviesIndexRouteImport } from './routes/_app.movies.index'
import { Route as AppEventsIndexRouteImport } from './routes/_app.events.index'
import { Route as AppDashboardIndexRouteImport } from './routes/_app.dashboard.index'
import { Route as AppCinemasIndexRouteImport } from './routes/_app.cinemas.index'
import { Route as AppBookingsIndexRouteImport } from './routes/_app.bookings.index'
import { Route as AppOrganizerScanRouteImport } from './routes/_app.organizer.scan'
import { Route as AppEventsCreateRouteImport } from './routes/_app.events.create'
import { Route as AppMoviesMovieIdIndexRouteImport } from './routes/_app.movies.$movieId.index'
import { Route as AppEventsEventIdIndexRouteImport } from './routes/_app.events.$eventId.index'
import { Route as AppCinemasCinemaIdIndexRouteImport } from './routes/_app.cinemas.$cinemaId.index'
import { Route as AppCheckoutShowtimeIdIndexRouteImport } from './routes/_app.checkout.$showtimeId.index'
import { Route as AppEventsEventIdEditRouteImport } from './routes/_app.events.$eventId.edit'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppMoviesIndexRoute = AppMoviesIndexRouteImport.update({
  id: '/movies/',
  path: '/movies/',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsIndexRoute = AppEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRoute,
} as any)
const AppCinemasIndexRoute = AppCinemasIndexRouteImport.update({
  id: '/cinemas/',
  path: '/cinemas/',
  getParentRoute: () => AppRoute,
} as any)
const AppBookingsIndexRoute = AppBookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizerScanRoute = AppOrganizerScanRouteImport.update({
  id: '/organizer/scan',
  path: '/organizer/scan',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsCreateRoute = AppEventsCreateRouteImport.update({
  id: '/events/create',
  path: '/events/create',
  getParentRoute: () => AppRoute,
} as any)
const AppMoviesMovieIdIndexRoute = AppMoviesMovieIdIndexRouteImport.update({
  id: '/movies/$movieId/',
  path: '/movies/$movieId/',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsEventIdIndexRoute = AppEventsEventIdIndexRouteImport.update({
  id: '/events/$eventId/',
  path: '/events/$eventId/',
  getParentRoute: () => AppRoute,
} as any)
const AppCinemasCinemaIdIndexRoute = AppCinemasCinemaIdIndexRouteImport.update({
  id: '/cinemas/$cinemaId/',
  path: '/cinemas/$cinemaId/',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckoutShowtimeIdIndexRoute =
  AppCheckoutShowtimeIdIndexRouteImport.update({
    id: '/checkout/$showtimeId/',
    path: '/checkout/$showtimeId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppEventsEventIdEditRoute = AppEventsEventIdEditRouteImport.update({
  id: '/events/$eventId/edit',
  path: '/events/$eventId/edit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof AppSettingsRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/events/create': typeof AppEventsCreateRoute
  '/organizer/scan': typeof AppOrganizerScanRoute
  '/bookings/': typeof AppBookingsIndexRoute
  '/cinemas/': typeof AppCinemasIndexRoute
  '/dashboard/': typeof AppDashboardIndexRoute
  '/events/': typeof AppEventsIndexRoute
  '/movies/': typeof AppMoviesIndexRoute
  '/events/$eventId/edit': typeof AppEventsEventIdEditRoute
  '/checkout/$showtimeId/': typeof AppCheckoutShowtimeIdIndexRoute
  '/cinemas/$cinemaId/': typeof AppCinemasCinemaIdIndexRoute
  '/events/$eventId/': typeof AppEventsEventIdIndexRoute
  '/movies/$movieId/': typeof AppMoviesMovieIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof AppSettingsRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/events/create': typeof AppEventsCreateRoute
  '/organizer/scan': typeof AppOrganizerScanRoute
  '/bookings': typeof AppBookingsIndexRoute
  '/cinemas': typeof AppCinemasIndexRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/events': typeof AppEventsIndexRoute
  '/movies': typeof AppMoviesIndexRoute
  '/events/$eventId/edit': typeof AppEventsEventIdEditRoute
  '/checkout/$showtimeId': typeof AppCheckoutShowtimeIdIndexRoute
  '/cinemas/$cinemaId': typeof AppCinemasCinemaIdIndexRoute
  '/events/$eventId': typeof AppEventsEventIdIndexRoute
  '/movies/$movieId': typeof AppMoviesMovieIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_app/events/create': typeof AppEventsCreateRoute
  '/_app/organizer/scan': typeof AppOrganizerScanRoute
  '/_app/bookings/': typeof AppBookingsIndexRoute
  '/_app/cinemas/': typeof AppCinemasIndexRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_app/events/': typeof AppEventsIndexRoute
  '/_app/movies/': typeof AppMoviesIndexRoute
  '/_app/events/$eventId/edit': typeof AppEventsEventIdEditRoute
  '/_app/checkout/$showtimeId/': typeof AppCheckoutShowtimeIdIndexRoute
  '/_app/cinemas/$cinemaId/': typeof AppCinemasCinemaIdIndexRoute
  '/_app/events/$eventId/': typeof AppEventsEventIdIndexRoute
  '/_app/movies/$movieId/': typeof AppMoviesMovieIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/settings'
    | '/login'
    | '/register'
    | '/events/create'
    | '/organizer/scan'
    | '/bookings/'
    | '/cinemas/'
    | '/dashboard/'
    | '/events/'
    | '/movies/'
    | '/events/$eventId/edit'
    | '/checkout/$showtimeId/'
    | '/cinemas/$cinemaId/'
    | '/events/$eventId/'
    | '/movies/$movieId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/settings'
    | '/login'
    | '/register'
    | '/events/create'
    | '/organizer/scan'
    | '/bookings'
    | '/cinemas'
    | '/dashboard'
    | '/events'
    | '/movies'
    | '/events/$eventId/edit'
    | '/checkout/$showtimeId'
    | '/cinemas/$cinemaId'
    | '/events/$eventId'
    | '/movies/$movieId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/forgot-password'
    | '/reset-password'
    | '/_app/settings'
    | '/_auth/login'
    | '/_auth/register'
    | '/_app/events/create'
    | '/_app/organizer/scan'
    | '/_app/bookings/'
    | '/_app/cinemas/'
    | '/_app/dashboard/'
    | '/_app/events/'
    | '/_app/movies/'
    | '/_app/events/$eventId/edit'
    | '/_app/checkout/$showtimeId/'
    | '/_app/cinemas/$cinemaId/'
    | '/_app/events/$eventId/'
    | '/_app/movies/$movieId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/movies/': {
      id: '/_app/movies/'
      path: '/movies'
      fullPath: '/movies/'
      preLoaderRoute: typeof AppMoviesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events/': {
      id: '/_app/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AppEventsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cinemas/': {
      id: '/_app/cinemas/'
      path: '/cinemas'
      fullPath: '/cinemas/'
      preLoaderRoute: typeof AppCinemasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bookings/': {
      id: '/_app/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof AppBookingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organizer/scan': {
      id: '/_app/organizer/scan'
      path: '/organizer/scan'
      fullPath: '/organizer/scan'
      preLoaderRoute: typeof AppOrganizerScanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events/create': {
      id: '/_app/events/create'
      path: '/events/create'
      fullPath: '/events/create'
      preLoaderRoute: typeof AppEventsCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/movies/$movieId/': {
      id: '/_app/movies/$movieId/'
      path: '/movies/$movieId'
      fullPath: '/movies/$movieId/'
      preLoaderRoute: typeof AppMoviesMovieIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events/$eventId/': {
      id: '/_app/events/$eventId/'
      path: '/events/$eventId'
      fullPath: '/events/$eventId/'
      preLoaderRoute: typeof AppEventsEventIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cinemas/$cinemaId/': {
      id: '/_app/cinemas/$cinemaId/'
      path: '/cinemas/$cinemaId'
      fullPath: '/cinemas/$cinemaId/'
      preLoaderRoute: typeof AppCinemasCinemaIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/checkout/$showtimeId/': {
      id: '/_app/checkout/$showtimeId/'
      path: '/checkout/$showtimeId'
      fullPath: '/checkout/$showtimeId/'
      preLoaderRoute: typeof AppCheckoutShowtimeIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events/$eventId/edit': {
      id: '/_app/events/$eventId/edit'
      path: '/events/$eventId/edit'
      fullPath: '/events/$eventId/edit'
      preLoaderRoute: typeof AppEventsEventIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppSettingsRoute: typeof AppSettingsRoute
  AppEventsCreateRoute: typeof AppEventsCreateRoute
  AppOrganizerScanRoute: typeof AppOrganizerScanRoute
  AppBookingsIndexRoute: typeof AppBookingsIndexRoute
  AppCinemasIndexRoute: typeof AppCinemasIndexRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppEventsIndexRoute: typeof AppEventsIndexRoute
  AppMoviesIndexRoute: typeof AppMoviesIndexRoute
  AppEventsEventIdEditRoute: typeof AppEventsEventIdEditRoute
  AppCheckoutShowtimeIdIndexRoute: typeof AppCheckoutShowtimeIdIndexRoute
  AppCinemasCinemaIdIndexRoute: typeof AppCinemasCinemaIdIndexRoute
  AppEventsEventIdIndexRoute: typeof AppEventsEventIdIndexRoute
  AppMoviesMovieIdIndexRoute: typeof AppMoviesMovieIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSettingsRoute: AppSettingsRoute,
  AppEventsCreateRoute: AppEventsCreateRoute,
  AppOrganizerScanRoute: AppOrganizerScanRoute,
  AppBookingsIndexRoute: AppBookingsIndexRoute,
  AppCinemasIndexRoute: AppCinemasIndexRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppEventsIndexRoute: AppEventsIndexRoute,
  AppMoviesIndexRoute: AppMoviesIndexRoute,
  AppEventsEventIdEditRoute: AppEventsEventIdEditRoute,
  AppCheckoutShowtimeIdIndexRoute: AppCheckoutShowtimeIdIndexRoute,
  AppCinemasCinemaIdIndexRoute: AppCinemasCinemaIdIndexRoute,
  AppEventsEventIdIndexRoute: AppEventsEventIdIndexRoute,
  AppMoviesMovieIdIndexRoute: AppMoviesMovieIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
